example/lib/DetectorViews/barcode_scanner_view.dart
example/lib/DetectorViews/digital_ink_recogniser_view.dart
example/lib/DetectorViews/label_detector_view.dart
example/lib/DetectorViews/pose_detector_view.dart
example/lib/DetectorViews/text_detector_view.dart
example/pubspec.lock
example/pubspec.yaml
example/test/widget_test.dart
lib/src/barcode_scanner.dart
lib/src/digital_ink_recognizer.dart
lib/src/google_ml_kit.dart
lib/src/label_detector.dart
lib/src/pose_detector.dart
lib/src/text_detector.dart
pubspec.lock
pubspec.yaml

null-safety

---

android/src/main/java/com/b/biradar/google_ml_kit/BarcodeDetector.java
example/lib/VisionDetectorViews/barcode_scanner_view.dart
lib/src/vision/barcode_scanner.dart

Barcode boundingBox is useful to show on a live camera

boundingBox

---

.idea/libraries/Dart_SDK.xml
example/android/app/build.gradle
example/ios/Flutter/Debug.xcconfig
example/ios/Flutter/Release.xcconfig
example/ios/Podfile
example/lib/VisionDetectorViews/camera_view.dart
example/lib/VisionDetectorViews/label_detector_view.dart
example/lib/VisionDetectorViews/painters/label_detector_painter.dart
example/lib/main.dart
example/pubspec.lock
example/pubspec.yaml
pubspec.lock

* Add camera plugin to get live feed.
* Select live feed or still image

Add live feed example for label detection

---

README.md
android/build.gradle
android/src/main/java/com/b/biradar/google_ml_kit/FaceProcessor.java
android/src/main/java/com/b/biradar/google_ml_kit/MlKitMethodCallHandler.java
example/android/app/build.gradle
example/lib/VisionDetectorViews/camera_view.dart
example/lib/VisionDetectorViews/detector_views.dart
example/lib/VisionDetectorViews/face_detector_view.dart
example/lib/VisionDetectorViews/label_detector_view.dart
example/lib/VisionDetectorViews/painters/face_detector_painter.dart
example/lib/main.dart
example/pubspec.lock
lib/src/vision/face_detector.dart
lib/src/vision/vision.dart
pubspec.yaml

* FaceDetector
* FaceProcessor in java
* FaceDetectorView
* FaceDetectorPainter
* Fixed InputImageRotation when using InputImage.fromBytes
* Updated README
* Bump version

Add Face Detection API  

---

README.md

Some of the example links present in the `Readme.md` file was not correct, have fixed those.

Fix example links in Readme 

---

README.md
example/ios/Podfile.lock
example/lib/main.dart
ios/Classes/GoogleMlKitPlugin.h
ios/Classes/GoogleMlKitPlugin.m
ios/Classes/vision/FaceProcessor.m
ios/Classes/vision/ImageLabeler.m
ios/google_ml_kit.podspec

*Fix expanded titles
* Update README

Add Image Labeling API in iOS

---

CHANGELOG.md
README.md
android/build.gradle
android/src/main/java/com/b/biradar/google_ml_kit/EntityExtractorApi.java
android/src/main/java/com/b/biradar/google_ml_kit/GenericModelManager.java
android/src/main/java/com/b/biradar/google_ml_kit/MlKitMethodCallHandler.java
android/src/main/java/com/b/biradar/google_ml_kit/OnDeviceTranslator.java
example/lib/NlpDetectorViews/entity_extraction_view.dart
example/lib/NlpDetectorViews/language_identifier_view.dart
example/lib/main.dart
example/pubspec.lock
lib/src/nlp/EntityExtraction.dart
lib/src/nlp/LanguageIdentifier.dart
lib/src/nlp/NaturalLanguage.dart
lib/src/nlp/OnDeviceTranslation.dart
pubspec.yaml

* Adds Entity Extraction for android
* Bumps pub version to 0.4

Add Entity Extraction

---

android/build.gradle
example/.gitignore
example/android/app/build.gradle

fix minSdkVersion: 21 

---

README.md
example/ios/Podfile.lock
example/lib/VisionDetectorViews/barcode_scanner_view.dart
example/lib/VisionDetectorViews/camera_view.dart
example/lib/VisionDetectorViews/face_detector_view.dart
example/lib/VisionDetectorViews/painters/barcode_detector_painter.dart
example/lib/VisionDetectorViews/painters/coordinates_translator.dart
example/lib/VisionDetectorViews/painters/face_detector_painter.dart
example/lib/main.dart
example/pubspec.lock
ios/Classes/GoogleMlKitPlugin.h
ios/Classes/GoogleMlKitPlugin.m
ios/Classes/vision/BarcodeDetector.m
ios/google_ml_kit.podspec
lib/src/vision/barcode_scanner.dart

Add Barcode scanning for iOS

---

README.md
android/build.gradle
android/src/main/java/com/b/biradar/google_ml_kit/MlKitMethodCallHandler.java
android/src/main/java/com/b/biradar/google_ml_kit/nl/SmartReply.java
android/src/main/java/com/b/biradar/google_ml_kit/vision/BarcodeDetector.java
example/lib/NlpDetectorViews/smart_reply_view.dart
example/lib/main.dart
lib/src/nlp/NaturalLanguage.dart
lib/src/nlp/SmartReply.dart
lib/src/vision/face_detector.dart

Add Smart Reply for android 

---

example/lib/VisionDetectorViews/painters/pose_painter.dart

This example of painting lines that connect joints will be useful for developers.

Add lines connecting body and arms

---

android/src/main/java/com/google_ml_kit/vision/BarcodeDetector.java
ios/Classes/vision/BarcodeScanner.m
lib/src/vision/barcode_scanner.dart
lib/src/vision/vision.dart

Add format to BarcodeValue

---

android/src/main/java/com/google_ml_kit/vision/BarcodeDetector.java
example/pubspec.lock
lib/src/vision/barcode_scanner.dart

Fix contact barcode and lint barcode doc comments

---

.gitignore
README.md
android/build.gradle
android/src/main/java/com/google_ml_kit/MlKitMethodCallHandler.java
android/src/main/java/com/google_ml_kit/vision/BarcodeDetector.java
android/src/main/java/com/google_ml_kit/vision/CustomRemoteModelManager.java
android/src/main/java/com/google_ml_kit/vision/ImageLabelDetector.java
example/.gitignore
example/lib/VisionDetectorViews/detector_views.dart
example/lib/VisionDetectorViews/label_detector_view.dart
example/lib/VisionDetectorViews/remote_model_view.dart
example/lib/main.dart
example/pubspec.lock
lib/src/vision/barcode_scanner.dart
lib/src/vision/label_detector.dart
lib/src/vision/object_detector.dart
lib/src/vision/vision.dart

Add firebase remote model support for image labelling

---

android/build.gradle
android/src/main/java/com/google_ml_kit/vision/PoseDetector.java
example/ios/Podfile.lock
ios/Classes/vision/PoseDetector.m
lib/src/vision/pose_detector.dart

Resolves issues - #90 , #93 for android.

Update Pose Detector API version and add 3d point feature

---

.gitignore
README.md
android/build.gradle
android/src/main/java/com/google_ml_kit/MlKitMethodCallHandler.java
android/src/main/java/com/google_ml_kit/vision/TextDetectorV2.java
example/lib/VisionDetectorViews/text_detectorv2_view.dart
example/lib/main.dart
lib/src/vision/text_detector.dart
lib/src/vision/vision.dart

Adds text recognition v2 for android - #130 
Note: all the scripts supported are statically linked hence there would again be increase 
of apk size of `4mb` per script added.

Add text recognition v2 for android

---

example/lib/VisionDetectorViews/camera_view.dart

Zoom option added in CameraView widget in Example project.

Zoom option added to CameraPreview in example app

---

android/build.gradle

Bump compile SDK version of android to 31 to support android 12

bump compile sdk version to 

---

CHANGELOG.md
packages/google_mlkit_digital_ink_recognition/CHANGELOG.md
packages/google_mlkit_digital_ink_recognition/README.md
packages/google_mlkit_digital_ink_recognition/android/src/main/java/com/google_mlkit_digital_ink_recognition/DigitalInkRecognizer.java
packages/google_mlkit_digital_ink_recognition/ios/Classes/GoogleMlKitDigitalInkRecognitionPlugin.m
packages/google_mlkit_digital_ink_recognition/lib/src/digital_ink_recognizer.dart
packages/google_mlkit_digital_ink_recognition/pubspec.yaml

* Add `DigitalInkRecognitionContext`.
* Add `WritingArea`.
* Update README.

google_mlkit_digital_ink_recognition - v0.4.0

---

packages/google_mlkit_text_recognition/android/build.gradle

changes ml kit version beta4 (android)

changes ml kit version beta4 (android)

---

packages/google_mlkit_commons/README.md

Adding also the necessary import statement.

Updating example code for camera image conversion.

---

CHANGELOG.md
packages/google_ml_kit/example/ios/Podfile.lock
packages/google_ml_kit/example/lib/nlp_detector_views/entity_extraction_view.dart
packages/google_mlkit_entity_extraction/CHANGELOG.md
packages/google_mlkit_entity_extraction/ios/Classes/GoogleMlKitEntityExtractionPlugin.m
packages/google_mlkit_entity_extraction/lib/src/entity_extractor.dart
packages/google_mlkit_entity_extraction/pubspec.yaml

google_mlkit_entity_extraction - v0.4.0

---

packages/google_ml_kit/example/android/build.gradle
packages/google_ml_kit/example/android/gradle/wrapper/gradle-wrapper.properties
packages/google_mlkit_barcode_scanning/android/build.gradle
packages/google_mlkit_commons/android/build.gradle
packages/google_mlkit_digital_ink_recognition/android/build.gradle
packages/google_mlkit_entity_extraction/android/build.gradle
packages/google_mlkit_entity_extraction/android/gradle/wrapper/gradle-wrapper.properties
packages/google_mlkit_face_detection/android/build.gradle
packages/google_mlkit_image_labeling/android/build.gradle
packages/google_mlkit_language_id/android/build.gradle
packages/google_mlkit_object_detection/android/build.gradle
packages/google_mlkit_pose_detection/android/build.gradle
packages/google_mlkit_selfie_segmentation/android/build.gradle
packages/google_mlkit_selfie_segmentation/android/gradle/wrapper/gradle-wrapper.properties
packages/google_mlkit_smart_reply/android/build.gradle
packages/google_mlkit_smart_reply/android/gradle/wrapper/gradle-wrapper.properties
packages/google_mlkit_text_recognition/android/build.gradle
packages/google_mlkit_translation/android/build.gradle
packages/google_mlkit_translation/android/gradle/wrapper/gradle-wrapper.properties

@bharat-biradar 
Updated:
- AGP: `7.2.1`
- Gradle: `7.4.2`
Tested via:
```
cd packages/google_ml_kit/example/
flutter build apk --debug
flutter run
```

Update AGP to 7.2.1

---

packages/google_mlkit_face_detection/README.md

Related to PR #211 where I added the possibilty to get the `headEulerAngleX` the documentation was not yet updated

Update Face detection Readme AngleX

---

packages/google_mlkit_barcode_scanning/lib/src/barcode_scanner.dart
packages/google_mlkit_face_detection/lib/src/face_detector.dart
packages/google_mlkit_object_detection/lib/src/object_detector.dart
packages/google_mlkit_text_recognition/lib/src/text_recognizer.dart

This pull requests should correct issues by "flutter analyze". This causes "Static code analysis" check error like #342 and #345 .

Fix "flutter analyze"  issues

---

packages/google_mlkit_face_detection/README.md

Updated the readme adding null safety!!
thanks

Updated Readme.

---

packages/google_ml_kit/pubspec.yaml
packages/google_mlkit_selfie_segmentation/CHANGELOG.md
packages/google_mlkit_selfie_segmentation/android/src/main/java/com/google_mlkit_selfie_segmentation/SelfieSegmenter.java
packages/google_mlkit_selfie_segmentation/lib/src/selfie_segmenter.dart
packages/google_mlkit_selfie_segmentation/pubspec.yaml

Optimize android result callback time

---

packages/google_mlkit_image_labeling/README.md

The Imagelabel property is label not text

fix: Update Readme on Image labeling

---

packages/google_mlkit_object_detection/README.md

List<DetectedObject> has a variable objects not _object

fix: Update Variable name

---

packages/google_mlkit_text_recognition/README.md

fix: Update README.md

---

packages/google_mlkit_face_detection/lib/src/face_detector.dart

close #363 
Now, The plugin cause below error.
```
packages/google_mlkit_face_detection/lib/src/face_detector.dart:103:9: Error: 'Rect' isn't a type.
final Rect boundingBox;
^^^^
```
So I added the `package:flutter/material.dart` import statement with this modification and changed the "package:flutter/services.dart" to be used only with methodCahnnel.

fix: modifed face_detector import class.

---

packages/google_mlkit_text_recognition/lib/src/text_recognizer.dart

Could not source Rect class due to missing import

fix: Imported material.dart for Rect class

---

packages/google_mlkit_object_detection/lib/src/object_detector.dart

same as #400, #401.
```
packages/google_mlkit_object_detection/lib/src/object_detector.dart:183:9: Error: Type 'Rect' not found.
final Rect boundingBox;
^^^^
```

fix: object_detector Imported material.dart for Rect class

---

packages/google_mlkit_language_id/lib/src/language_identifier.dart

fix: indexifyLanguage which requires an id

---

CHANGELOG.md
packages/example/android/app/build.gradle
packages/example/ios/Podfile
packages/example/ios/Podfile.lock
packages/example/lib/vision_detector_views/camera_view.dart
packages/example/lib/vision_detector_views/text_detector_view.dart
packages/example/pubspec.lock
packages/google_mlkit_commons/ios/Classes/GoogleMlKitCommonsPlugin.m
packages/google_mlkit_text_recognition/CHANGELOG.md
packages/google_mlkit_text_recognition/README.md
packages/google_mlkit_text_recognition/android/src/main/java/com/google_mlkit_text_recognition/TextRecognizer.java
packages/google_mlkit_text_recognition/ios/Classes/GoogleMlKitTextRecognitionPlugin.m
packages/google_mlkit_text_recognition/lib/src/text_recognizer.dart
packages/google_mlkit_text_recognition/pubspec.yaml

* Fix: Confidence and angle only available for Android.
* Feat: Add `TextSymbol`, only available for Android.

fix: hotfix for google_mlkit_text_recognition

---

packages/google_mlkit_language_id/README.md

Changed "imageLabeler.close()" by "languageIdentifier.close()".

fix: Changed "imageLafbeler.close()" by "languageIdentifier.close()"

---

packages/google_mlkit_smart_reply/android/build.gradle

fix: namespace typo in smart reply gradle

---

packages/example/ios/Podfile.lock
packages/example/lib/vision_detector_views/document_scanner_view.dart
packages/example/pubspec.lock
packages/example/pubspec.yaml
packages/google_mlkit_document_scanner/README.md
packages/google_mlkit_document_scanner/android/src/main/java/com/google_mlkit_document_scanner/DocumentScanner.java
packages/google_mlkit_document_scanner/android/src/main/java/com/google_mlkit_document_scanner/GoogleMlKitDocumentScannerPlugin.java
packages/google_mlkit_document_scanner/lib/src/document_scanner.dart

- return DocumentScanningResult
- refactor example app
- refactor Android native plugin: DocumentScanner.java and GoogleMlKitDocumentScannerPlugin.java

feat: DocumentScanner returns DocumentScanningResult

---

packages/google_mlkit_entity_extraction/android/build.gradle
packages/google_mlkit_face_detection/android/build.gradle
packages/google_mlkit_face_mesh_detection/android/build.gradle
packages/google_mlkit_image_labeling/android/build.gradle
packages/google_mlkit_language_id/android/build.gradle
packages/google_mlkit_object_detection/android/build.gradle
packages/google_mlkit_pose_detection/android/build.gradle
packages/google_mlkit_selfie_segmentation/android/build.gradle
packages/google_mlkit_smart_reply/android/build.gradle

chore: Update Android dependencies.

---

packages/google_mlkit_text_recognition/README.md

Multiple app crashes has been reported due to outdated dependencies. This PR is just to update the language package dependencies written inside the documentation, so people won't be confused anymore. 
- Resolve #519 
- Resolve #549

docs: Update readme.md for text recognition

---

packages/google_mlkit_commons/CHANGELOG.md
packages/google_mlkit_commons/android/src/main/java/com/google_mlkit_commons/GoogleMlKitCommonsPlugin.java
packages/google_mlkit_commons/android/src/main/java/com/google_mlkit_commons/InputImageConverter.java
packages/google_mlkit_commons/pubspec.yaml

to solve this issue https://github.com/flutter-ml/google_ml_kit_flutter/issues/534

fix: Handle NullPointerException and some wanring at google_mlkit_commons

---

packages/example/android/gradle/wrapper/gradle-wrapper.properties
packages/example/android/settings.gradle
packages/example/pubspec.lock

Fixed Gradle settings and Android SDK configuration to enable 'flutter run' with connected Android device.

build: Fixed Gradle settings and Android SDK configuration
